### ISSUE TITLE
KeyNotFoundException thrown for MT receive endpoints.

### ISSUE THREAD

**Issue by Crozin** [MassTransit/GreenPipes#17]
I'm running fairly standard setup of MT using AmazonSQS as transport layer. It seems that from time to time one service starts to fail critically due to some bug in GreenCache.

Could not detect any unexpected/unusual behavior happening prior to failure. Some stack traces:

```
System.Collections.Generic.KeyNotFoundException: Key not found: <<RECEIVE_ENDPOINT_NAME>>
   at GreenPipes.Caching.Internals.Index`2.Get(TKey key, MissingValueFactory`2 missingValueFactory)
   at MassTransit.AmazonSqsTransport.Contexts.AmazonSqsClientContext.MassTransit.AmazonSqsTransport.ClientContext.DeleteMessage(String queueName, String receiptHandle, CancellationToken cancellationToken)
   at MassTransit.Transports.ReceivePipeDispatcher.Dispatch(ReceiveContext context, ReceiveLockContext receiveLock)
```

```
System.Collections.Generic.KeyNotFoundException: <<RECEIVE_ENDPOINT_NAME_error>>
   at GreenPipes.Caching.Internals.Index`2.Get(TKey key, MissingValueFactory`2 missingValueFactory)
   at MassTransit.AmazonSqsTransport.Contexts.AmazonSqsClientContext.MassTransit.AmazonSqsTransport.ClientContext.CreateSendRequest(String queueName, Byte[] body)
   at MassTransit.AmazonSqsTransport.Transport.SqsMoveTransport.Move(ReceiveContext context, Action`2 preSend)
   at MassTransit.Pipeline.Filters.ErrorTransportFilter.GreenPipes.IFilter<MassTransit.ExceptionReceiveContext>.Send(ExceptionReceiveContext context, IPipe`1 next)
   at MassTransit.Pipeline.Filters.GenerateFaultFilter.GreenPipes.IFilter<MassTransit.ExceptionReceiveContext>.Send(ExceptionReceiveContext context, IPipe`1 next)
   at GreenPipes.Filters.RescueFilter`2.GreenPipes.IFilter<TContext>.Send(TContext context, IPipe`1 next)
   at MassTransit.Pipeline.Filters.DeadLetterFilter.GreenPipes.IFilter<MassTransit.ReceiveContext>.Send(ReceiveContext context, IPipe`1 next)
   at MassTransit.Transports.ReceivePipeDispatcher.Dispatch(ReceiveContext context, ReceiveLockContext receiveLock)
   at MassTransit.Transports.ReceivePipeDispatcher.Dispatch(ReceiveContext context, ReceiveLockContext receiveLock)
   at MassTransit.Transports.ReceivePipeDispatcher.Dispatch(ReceiveContext context, ReceiveLockContext receiveLock)
   at MassTransit.AmazonSqsTransport.Pipeline.AmazonSqsBasicConsumer.HandleMessage(Message message)
```

Reporting here, having no idea whatsoever so far what might cause such behavior.

**Comment by phatboyg** [comment]
I'm pretty sure I know what this is, related to how it keeps the ARN names cached. It's a trade off, since it is likely that users with request/response end up with a lot of names in there and cache expiration is necessary. It should try to resolve it though, so I'll have to see what's up. But I think I know right where it is, the challenge is knowing how to rebuild that entry when requested...

**Comment by phatboyg** [comment]
Can you put this in MassTransit, so I can assign it to Amazon SQS. It isn't green cache.
